### ISSUE TITLE
 stored type DataFrames.Index does not match currently loaded type

### ISSUE THREAD

**Issue by floswald** [timholy/HDF5.jl#158]
hi!
i'm not sure how to get around this error. I save a dict with several dataframes in one session from within `Module mig`. then in another session i want to load the object. Am I doing something wrong here?

```
using mig
julia> d=mig.load("/Users/florianoswald/git/migration/data/exp_shockp.JLD")
ERROR: stored type DataFrames.Index does not match currently loaded type
```

`mig` is

```
using GLM, MOpt.transpose, PDMats, Distributions, DataFrames, DataFramesMeta, ApproXD, Lazy, Optim, HDF5, JLD
```

**Comment by simonster** [comment]
This should have been fixed for the JLD 0.1+ format along with #198. Ideally we should make the same change in the JLD 0.0 reader (#205).
