### ISSUE TITLE
Saving tuple-within-tuple like (1,(2,3)) fails

### ISSUE THREAD

**Issue by rened** [timholy/HDF5.jl#196]
In julia 0.3.4 using HDF5 master, saving a tuple works, but not when it itself contains a tuple. Am I overlooking something or should this work in principle?

```jl
julia> save("/tmp/tst.jld", "a", (1,2))

julia> save("/tmp/tst.jld", "a", (1,(2,3)))
ERROR: T not defined
 in h5type at /Users/rene/.julia/v0.3/HDF5/src/jld_types.jl:288
 in write_compound at /Users/rene/.julia/v0.3/HDF5/src/JLD.jl:674
 in write at /Users/rene/.julia/v0.3/HDF5/src/JLD.jl:484
 in anonymous at /Users/rene/.julia/v0.3/HDF5/src/JLD.jl:967
 in jldopen at /Users/rene/.julia/v0.3/HDF5/src/JLD.jl:237
 in save at /Users/rene/.julia/v0.3/HDF5/src/JLD.jl:965
```

**Comment by simonster** [comment]
Hmm. The easy fix here would be to remove the checks that reject tuples of non-datatypes. However, it might be more efficient to flatten tuples of tuples, since the type of the outer tuple determines the type of the inner tuple and the inner tuple cannot be undefined.

**Comment by simonster** [comment]
This now works. We should still flatten the tuple, but that will happen when we switch to storing bits types tuples inline (and drop 0.3 support).
