### ISSUE TITLE
Compiling on w7

### ISSUE THREAD

**Issue by dolejm1** [timholy/HDF5.jl#199]
I've got this error:

  | | |_| | | | (_| |  |  Version 0.3.2+2 (2014-10-22 01:21 UTC)
 _/ |\__'_|_|_|\__'_|  |  release-0.3/6babc84* (fork: 180 commits, 148 days)
|__/                   |  x86_64-w64-mingw32

julia> Pkg.build("HDF5")
INFO: Building Blosc
INFO: Building WinRPM
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.xml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.xml
INFO: Building HDF5
INFO: Packages to update:  zlib1
INFO: Packages to install: hdf5
INFO: Downloading: zlib1
INFO: Extracting: zlib1

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\Users\dolejm1\.julia\v0.3\WinRPM\cache\2\noarch%2Fmingw64-zlib1-1.2.8-8.1.noarch.cpio

ERROR: Can not delete output file C:\Users\dolejm1\.julia\v0.3\WinRPM\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\zlib1.dll

Sub items Errors: 1

========================================================[ ERROR: HDF5 ]=========================================================

failed process: Process(`7z x -y 'C:\Users\dolejm1\.julia\v0.3\WinRPM\cache\2\noarch%2Fmingw64-zlib1-1.2.8-8.1.noarch.cpio' '-oC
:\Users\dolejm1\.julia\v0.3\WinRPM\deps'`, ProcessExited(2)) [2]
while loading C:\Users\dolejm1\.julia\v0.3\HDF5\deps\build.jl, in expression starting on line 23

================================================================================================================================

========================================================[ BUILD ERRORS ]========================================================

WARNING: HDF5 had build errors.

 - packages with build errors remain installed in C:\Users\dolejm1\.julia\v0.3
 - build a package and all its dependencies with `Pkg.build(pkg)`
 - build a single package by running its `deps/build.jl` script

================================================================================================================================

**Comment by tkelman** [comment]
Is that file at C:\Users\dolejm1.julia\v0.3\WinRPM\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\zlib1.dll present? Does it look intact? Can you manually delete it? If the file is locked and in use by some running process, can you try closing all Julia processes, or using a file unlocker utility?

**Comment by dolejm1** [comment]
It is present.
It looks intact.
It can not be deleted because it is opened by Julia
It builds on fresh Julia.

**Comment by tkelman** [comment]
So are things functioning now? Should we close the issue? We probably need to more clearly state somewhere in base Julia's package documentation to first try `Pkg.build("<...>")` when things aren't working. This only applies to packages that rely on binary dependencies, but I think that distinction isn't immediately clear to most new users.

**Comment by dolejm1** [comment]
Yes. The hint is update and build packages before using any other package. It can lock resources to be updated or changed during the build.

**Comment by tkelman** [comment]
If we could figure out what piece of code is holding the file open, maybe we could do something about it. Might be tough to find though.

**Comment by timholy** [comment]
One could do worse than say "close all open julia sessions and try `Pkg.build("BrokenPkg")`."
