### ISSUE TITLE
Translate between Core.Nothing and Core.Void

### ISSUE THREAD

**Issue by simonster** [timholy/HDF5.jl#218]
@timholy added code to perform special serialization of Nothing/Void, but we're still reconstructing these types when reading JLD files created with older versions of JLD instead of mapping them to their new names (e.g. JuliaLang/julia#10289). We could do this with a regexp hack like what we have for UInt, but it would be better to have a general solution that doesn't have the potential to cause problems with user-defined types. The same probably holds for String/AbstractStrings. Related to #204.

**Comment by timholy** [comment]
Yes, I've been also thinking we need a general translation infrastructure. Might also help with #209.
