### ISSUE TITLE
Can't precompile HDF5 on OSX

### ISSUE THREAD

**Issue by rened** [timholy/HDF5.jl#229]
Precompiling `HDF5` works fine on Linux, and I can precompile other packages like `Images` and `Nettle` just fine under OSX, but not `HDF5`.

Using
```
 - BinDeps                       0.3.10
 - Homebrew                      0.1.14             
 - HDF5                          0.4.13
```
I get
```
precompile.jl
error during bootstrap: LoadError(at "sysimg.jl" line 286: LoadError(at "/Users/rene/local/julia/base/userimg.jl" line 1: LoadError(at "/Users/rene/.julia/v0.3/HDF5/src/HDF5.jl" line 1: LoadError(at "/Users/rene/.julia/v0.3/HDF5/src/plain.jl" line 15: LoadError(at "/Users/rene/.julia/v0.3/Homebrew/src/Homebrew.jl" line 353: UndefVarError(var=:STDERR))))))
make[1]: *** [/Users/rene/local/julia/usr/lib/julia/sys0.o] Error 1
make: *** [release] Error 2
```
Versioninfo:
```
Julia Version 0.3.7
Commit cb9bcae* (2015-03-23 21:36 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
I'd be grateful for suggestions on how to further debug this. Thanks!
cc @staticfloat

**Comment by rened** [comment]
ps: precompiling `Blosc` only works just fine.

**Comment by staticfloat** [comment]
Hrmmmm.... that backtrace is strange as it looks to me like it's complaining about a missing variable `STDERR` in `Homebrew.jl`, but `Homebrew.jl` doesn't ever use the string `STDERR` outside of a comment.

**Comment by rened** [comment]
I believe this is because Julia wants to print the output of some error - if I knew how to get to the original error I could move on. The problem is that this error occurs even before `Homebrew` code gets executed. I tried putting print statements in `Homebrew.jl`, but the error comes already when `HDF5` includes `Homebrew` in its `build.jl`. This is confusing to me, as `using Homebrew` works fine for `Images`, `Nettle` etc ...

**Comment by rened** [comment]
turns out, there was a superfluous `import Homebrew` in `plain.jl` - when I remove that precompilation works just fine
