### ISSUE TITLE
Should JLD be separated from HDF5?

### ISSUE THREAD

**Issue by sebastiang** [timholy/HDF5.jl#233]
I'm sure it's been considered; thought it might make sense for consumers (as I plan to be) of the HDF interface but not the JLD cleverness.

**Comment by simonster** [comment]
Dup of #137. The consensus there seemed to be that it should be split into a second package, but it hasn't happened yet.

**Comment by timholy** [comment]
Code reorganizations can be painful (e.g., Base.Graphics->Graphics) with very little short-term advantage, so I have been dragging my heels and just busy with higher priorities. But I still think it should happen someday when I have a week to deal with the fallout.

**Comment by simonster** [comment]
In this case I think the code reorganization should be relatively painless. Packages that need JLD would need to add it to their REQUIRE files, but otherwise I don't think it would be necessary to make any changes to existing code, since `using HDF5, JLD` would continue to work.

**Comment by timholy** [comment]
I was also entertaining notions of going through old issues and pull requests and addressing as many of them as possible before splitting, since I don't think the issue history can be migrated. But perhaps that's not necessary.
