### ISSUE TITLE
Cannot persist number to string dicts in windows, can persist string to numbers dict just fine

### ISSUE THREAD

**Issue by mAch17** [timholy/HDF5.jl#238]
Hi,

I am a noob in Julia, so I might be making some big wrong assumption or error.
The corresponding code for Dict{Int64,String} works just fine. (Julia 0.4 on Windows 8)

julia> x = {1=>"alp",2=>"blp"}

WARNING: deprecated syntax "{a=>b, ...}".
Use "Dict{Any,Any}(a=>b, ...)" instead.
Dict{Any,Any} with 2 entries:
  2 => "blp"
  1 => "alp"

julia> using HDF5,JLD

julia> save("maxmax",x)
ERROR: MethodError: `bytestring` has no method matching bytestring(::Int64)
 in anonymous at C:\Users\sony\.julia\v0.4\HDF5\src\JLD.jl:1036
 in jldopen at C:\Users\sony\.julia\v0.4\HDF5\src\JLD.jl:233
 in save at C:\Users\sony\.julia\v0.4\HDF5\src\JLD.jl:1033

**Comment by timholy** [comment]
You want to use `save("maxmax", "x", x)`. When you pass only a dict, the keys of the dict are taken as the names of the variables. That's not your intention here, so you need to give a name for the variable in the HDF5 file.

**Comment by mAch17** [comment]
Thanks a tonne. This works :) . Sorry for raising an issue with something this stupid.

**Comment by timholy** [comment]
Actually, if you think it's under-documented, please edit the docs to make them better! (You can do that straight from your web browser, see https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#improving-documentation

**Comment by mAch17** [comment]
Sure, will do. Thanks again.

**Comment by timholy** [comment]
I think I was too hasty to close this; at a minimum we could improve the error message.
