### ISSUE TITLE
Error loading DataFrames on Julia v0.3.10

### ISSUE THREAD

**Issue by shashi** [timholy/HDF5.jl#244]
Here is what happens:
on Julia master (works fine):
```julia
julia> using HDF5, JLD, DataFrames
julia> load("splitup/20140203/1/eA/data.jld")["df"]
22499x16 DataFrames.DataFrame
| Row   | symbol         | listexgidx | repexgidx | sessid | tpflag | tcflag | tcidx | tvoltype | tbate | tsize  | texgseq | trecsback | ttotalvol | ttickvol | price  | systime                 |
|-------|----------------|------------|-----------|--------|--------|--------|-------|----------|-------|--------|---------|-----------|---
...
```

on 0.3.10
```julia
julia> using HDF5, JLD, DataFrames

julia> load("splitup/20140203/1/eA/data.jld")["df"]
WARNING: type DataArrays.DataArray{Dates.DateTime,1} not present in workspace; reconstructing
WARNING: type Dates.DateTime not present in workspace; reconstructing
WARNING: type Dates.UTInstant{Dates.Millisecond} not present in workspace; reconstructing
WARNING: type Dates.Millisecond not present in workspace; reconstructing
Error showing value of type DataFrame:
ERROR: `isna` has no method matching isna(::##DataArrays.DataArray{Dates.DateTime,1}#23978, ::Int64)
 in getmaxwidths at /home/shashi/.julia/v0.3/DataFrames/src/abstractdataframe/show.jl:116
 in show at /home/shashi/.julia/v0.3/DataFrames/src/abstractdataframe/show.jl:451
 in show at /home/shashi/.julia/v0.3/DataFrames/src/abstractdataframe/show.jl:439
 in anonymous at show.jl:1159
```

Am I doing it right?

**Comment by shashi** [comment]
But the dataframe does load -- I can access individual columns just fine.

**Comment by timholy** [comment]
The message suggests that the error is happening when you're displaying the result in the REPL---note that it's triggered in `show.jl` and that no file in HDF5/JLD appears in the backtrace. Consequently, I suspect this is a bug in DataFrames, not HDF5.

If this analysis proves incorrect, let me know and we'll reopen this.

**Comment by shashi** [comment]
From
```julia
ERROR: `isna` has no method matching isna(::##DataArrays.DataArray{Dates.DateTime,1}#23978
```

I thought it's because of the gensym type. I suspected that is not a DataFrames issue...

**Comment by timholy** [comment]
Oh, now I get your point. Does it help to first say `using Dates, DataArrays`?

**Comment by simonster** [comment]
The main problem is that JLD doesn't know what a DateTime is because the Dates module is not loaded. (It is part of Base on master, which is why this doesn't happen there.)

The way JLD reconstructs the parametric type `DataArrays.DataArray{Dates.DateTime,1}` when Dates is gone is not completely wrong but is suboptimal. Presumably all the data in objects of the gensym types is accessible, but fewer methods work on them than possibly could. It would be better to reconstruct `Dates.DateTime` first before attempting to reconstruct `DataArrays.DataArray{Dates.DateTime,1}`.

**Comment by timholy** [comment]
Also relevant: https://github.com/timholy/HDF5.jl/blob/master/doc/jld.md#types-and-their-definitions (see the part about `addrequire`).
