### ISSUE TITLE
Can't  build HDF5

### ISSUE THREAD

**Issue by meaningofshape** [timholy/HDF5.jl#245]
When trying 'using MAT' I am getting an error, "HDF5 not properly installed. Please run Pkg.build("HDF5)..." .  But when I attempt this build, it gets hung up on 'INFO: Building Blosc'.  Can you provide any advice on this?  
Thank you.

**Comment by timholy** [comment]
Can you file this with https://github.com/stevengj/Blosc.jl?

**Comment by meaningofshape** [comment]
Ok
